---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: coreos-hypervisor
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-hci
image-version: stable-zfs # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    group-remove:
      packages:
        - NetworkManager-wifi
        - atheros-firmware
        - brcmfmac-firmware
        - iwlegacy-firmware
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - mt7xxx-firmware
        - nxpwireless-firmware
        - realtek-firmware
        - tiwilink-firmware

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

